#!/usr/bin/env php
<?php
require __DIR__ . '/locito-base/vendor/autoload.php';
use Symfony\Component\Console\Application;

$application = new Application();

# add our commands
$application->add(new GreetCommand());
$application->add(new MakeAll());
$application->add(new MakeTable());
$application->add(new MakeModel());
$application->add(new MakeController());
$application->add(new MakeLocalization());
$application->add(new MakeView());
$application->add(new DatabaseBuild());
$application->add(new AppUpdate());
$application->add(new ClearTemp());
$application->add(new ClearCache());
$application->add(new ClearAll());
$application->add(new PluginsUpdate());
$application->add(new MakeSeeder());

$application->run();
?>